create table if not exists public.postpilot_project_versions (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.postpilot_projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  snapshot jsonb not null,
  created_at timestamptz not null default now(),
  constraint postpilot_project_versions_snapshot_size_check
    check (octet_length(snapshot::text) <= 180000)
);

create index if not exists postpilot_project_versions_project_created_idx
  on public.postpilot_project_versions(project_id, created_at desc);

alter table public.postpilot_project_versions enable row level security;

drop policy if exists "postpilot versions select own" on public.postpilot_project_versions;
create policy "postpilot versions select own"
on public.postpilot_project_versions for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "postpilot versions insert own" on public.postpilot_project_versions;
create policy "postpilot versions insert own"
on public.postpilot_project_versions for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1 from public.postpilot_projects p
    where p.id = project_id and p.user_id = (select auth.uid())
  )
);

drop policy if exists "postpilot versions delete own" on public.postpilot_project_versions;
create policy "postpilot versions delete own"
on public.postpilot_project_versions for delete
to authenticated
using ((select auth.uid()) = user_id);

grant select, insert, delete on public.postpilot_project_versions to authenticated;
